
version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rocketpay
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080